hp_enemy1 = HpEnemy;
cd_shoot = 0;
cd_collision = 0;
cd_random_direction = 0; // кулдаун для изменения направления движения
EnemyCount += 1;
speedenemydefolt = SpeedEnemy;
random_direction = irandom_range(1,2);
cd_enemy_walk = 0;
cd_snd_player_ouch = 0;